cooking/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
from .views import *

app_name = "cooking"

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("category/<int:pk>/", PostsByCategory.as_view(), name="category_list"),
    path("post/<int:pk>/", PostDetail.as_view(), name="post_detail"),
    path("post/<int:pk>/update/", PostUpdate.as_view(), name="post_update"),
    path("post/<int:pk>/delete/", PostDelete.as_view(), name="post_delete"),
    path("add_post/", AddPost.as_view(), name="add_post"),
    path("search/", SearchResults.as_view(), name="search"),
    path("change_password/", UserChangePassword.as_view(), name="change_password"),

    path("post/<int:pk>/add_comment/", add_comment, name="add_comment"),
    path("login/", user_login, name="login"),
    path("logout/", user_logout, name="logout"),
    path("register/", user_register, name="register"),
    path("profile/<int:user_id>/", profile, name="profile"),

    # API
    path("api/posts/", PostListAPI.as_view(), name="posts_list_api"),
    path("api/posts/<int:pk>/", PostDetailAPI.as_view(), name="posts_detail_api"),
    path("api/categories/", CategoryListAPI.as_view(), name="category_list_api"),
    path("api/categories/<int:pk>/", CategoryDetailAPI.as_view(), name="category_detail_api"),

    # JWT
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

culinary/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("cooking.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cooking/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Category(models.Model):
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("cooking:category_list", kwargs={"pk": self.pk})


class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField(default="soon...")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    photo = models.ImageField(upload_to="photos/", blank=True, null=True)
    watched = models.IntegerField(default=0)
    is_published = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="posts")
    author = models.ForeignKey(User, default=None, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return f"Post: {self.title}, pk: {self.pk}"

    def get_absolute_url(self):
        return reverse("cooking:post_detail", kwargs={"pk": self.pk})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

cooking/forms.py
from django import forms
from .models import Post, Comment
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class PostAddForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title", "content", "category", "photo")
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "content": forms.Textarea(attrs={"class": "form-control", "placeholder": "Add description"}),
            "category": forms.Select(attrs={"class": "form-control"}),
            "photo": forms.FileInput(attrs={"class": "form-control"}),
        }


class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username",
                               max_length=127,
                               widget=forms.TextInput(attrs={"class": "form-control"}),
                               )
    password = forms.CharField(label="Password",
                               widget=forms.PasswordInput(attrs={"class": "form-control"}),
                               )


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    username = forms.CharField(max_length=127,
                               widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Username"}))
    email = forms.EmailField(widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Email"}))
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "Password"}))
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "Confirm Password"}))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)
        widgets = {
            "text": forms.Textarea(attrs={"class": "form-control",
                                          "placeholder": "Comment here",
                                          })
        }

cooking/views.py
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import F, Q
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import login, logout
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from rest_framework.generics import ListAPIView, RetrieveAPIView
from rest_framework.permissions import IsAuthenticated

from .models import Post, Category, Comment
from .forms import PostAddForm, LoginForm, RegistrationForm, CommentForm
from .serializers import PostSerializer, CategorySerializer


class Index(ListView):
    queryset = Post.objects.filter(is_published=True)
    context_object_name = "posts"
    template_name = "cooking/index.html"
    extra_context = {"title": "Recipes"}


class PostsByCategory(Index):
    def get_queryset(self):
        return Post.objects.filter(category_id=self.kwargs["pk"], is_published=True)

    def get_context_data(self, *, object_list=..., **kwargs):
        context = super().get_context_data()
        category = get_object_or_404(Category, pk=self.kwargs["pk"])
        context["title"] = category.title
        return context


class PostDetail(DetailView):
    template_name = "cooking/post_detail.html"

    def get_queryset(self):
        return Post.objects.filter(pk=self.kwargs["pk"])

    def get_context_data(self, **kwargs):
        Post.objects.filter(pk=self.kwargs["pk"]).update(watched=F("watched") + 1)
        context = super().get_context_data()
        post = self.object
        context["title"] = post.title
        post_recommends = Post.objects.exclude(pk=self.kwargs["pk"]).order_by("-watched")[:5]
        context["post_recommends"] = post_recommends
        if self.request.user.is_authenticated:
            context["comment_form"] = CommentForm

        context["comments"] = Comment.objects.filter(post=post)
        return context


class AddPost(CreateView):
    form_class = PostAddForm
    template_name = "cooking/add_post.html"
    extra_context = {"title": "Add post"}

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdate(UpdateView):
    model = Post
    form_class = PostAddForm
    template_name = "cooking/add_post.html"
    extra_context = {"title": "Update post"}


class PostDelete(DeleteView):
    model = Post
    success_url = reverse_lazy("cooking:index")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.is_published = False
        self.object.save()
        return HttpResponseRedirect(success_url)


class SearchResults(Index):
    def get_queryset(self):
        word = self.request.GET.get("q")
        posts = Post.objects.filter(
            Q(title__icontains=word) | Q(content__icontains=word)
        )
        return posts


class UserChangePassword(PasswordChangeView):
    template_name = "cooking/password_change_form.html"
    success_url = reverse_lazy("cooking:index")


def add_comment(request: HttpRequest, pk) -> HttpResponse:
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.post = Post.objects.get(pk=pk)
        comment.save()
        messages.success(request, "Your comment has been successfully added")
    return redirect("cooking:post_detail", pk)


def user_login(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = LoginForm(data=request.POST)
        if form.is_valid():
            print("for is valid")
            user = form.get_user()
            login(request, user)  # without authenticate because it has inside form
            messages.success(request, "You have successfully logged in")
            return redirect("cooking:index")
    else:
        form = LoginForm()
    context = {
        "title": "Login",
        "form": form,
    }
    return render(request, "cooking/login_form.html", context=context)


def user_logout(request: HttpRequest) -> HttpResponse:
    logout(request)
    return redirect("cooking:index")


def user_register(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = RegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("cooking:login")
    else:
        form = RegistrationForm()
    context = {
        "form": form,
        "title": "Register"
    }
    return render(request, "cooking/user_register.html", context=context)


def profile(request, user_id):
    user = User.objects.get(pk=user_id)
    posts = Post.objects.filter(author=user)
    context = {
        "user": user,
        "posts": posts,
    }
    return render(request, "cooking/profile.html", context=context)


class PostListAPI(ListAPIView):
    queryset = Post.objects.filter(is_published=True)
    serializer_class = PostSerializer


class PostDetailAPI(RetrieveAPIView):
    queryset = Post.objects.filter(is_published=True)
    serializer_class = PostSerializer
    permission_classes = (IsAuthenticated,)


class CategoryListAPI(ListAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


class CategoryDetailAPI(RetrieveAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

cooking/templates/cooking/add_post.html
{% extends "base.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block main %}
    <div class="d-flex justify-content-center">
        <div class="card col-8 mb-4 mt-4">
            <div class="card-body">
                <h2 class="text-center">
                    {% if "update" in request.path %}
                        Update post
                    {% else %}
                        Add new post
                    {% endif %}
                </h2>
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-dark" type="submit">
                        {% if "update" in request.path %}
                            Update
                        {% else %}
                            Add
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>
    <div>
        <div style="margin-top: 100px;"></div>
    </div>
{% endblock %}

cooking/templates/cooking/index.html
{% extends "base.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block main %}
    <h2>Recipes</h2>
    <div class="d-flex justify-content-between">
        {% include "cooking/components/category_buttons.html" %}
        {% include "cooking/components/posts_list.html" %}
    </div>
{% endblock %}

cooking/templates/cooking/login_form.html
{% extends "base.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block main %}
    <div>
        <div style="margin-top: 200px;"></div>
    </div>
    <div class="d-flex justify-content-center">
        <div class="card col-4 mb-4 mt-4">
            <div class="card-body">
                <h2 class="text-center">Login</h2>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-dark" type="submit">Login</button>
                </form>
            </div>
        </div>
    </div>
    <div>
        <div style="margin-top: 280px;"></div>
    </div>
{% endblock %}

cooking/templates/cooking/password_change_form.html
{% extends 'base.html' %}
{% block title %}
    Change password
{% endblock %}

{% block main %}
    <div>
        <div style="margin-top: 200px"></div>
    </div>
    <h1>Change password</h1>

    <form action="." method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <p><input type="submit" value="Change password"></p>
    </form>
    <div>
        <div style="margin-top: 250px"></div>
    </div>
{% endblock %}

cooking/templates/cooking/post_confirm_delete.html
{% extends "base.html" %}

{% block main %}
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete the post with the title: "{{ post.title }}"?</p>
        <input type="submit" value="Yes, delete" class="btn btn-danger">
        <a href="{{ post.get_absolute_url }}" class="btn btn-dark">Back</a>
    </form>
    <div>
        <div style="margin-top: 720px;"></div>
    </div>
{% endblock %}

cooking/templates/cooking/post_detail.html
{% extends "base.html" %}
{% block title %}
    {{ title }}
{% endblock %}
{% block main %}
    <main>
        <div class="d-flex justify-content-between">
            <div class="col-8">
                <div class="card">
                    <div class="card-header d-flex justify-content-between">{{ post.category }}
                        <div>
                            {% if request.user == post.author %}
                                <a href="{% url 'cooking:post_delete' pk=post.pk %}" class="btn btn-dark">Delete</a>
                                <a href="{% url 'cooking:post_update' pk=post.pk %}" class="btn btn-dark">Change</a>
                            {% endif %}
                            <a href="{% url 'cooking:category_list' pk=post.category.pk %}"
                               class="btn btn-dark">Back</a>
                        </div>
                    </div>
                    <div class="card-body">
                        {% if post.photo %}
                            <img src="{{ post.photo.url }}" width="300"
                                 alt="">
                        {% else %}
                            <img src="https://i0.wp.com/castlewoodassistedliving.com/wp-content/uploads/2021/01/image-coming-soon-placeholder.png?fit=1000%2C1000&ssl=1"
                                 width="300"
                                 alt="">
                        {% endif %}
                        <h5 class="card-title">{{ post.title }}</h5>
                        <p class="card-text">
                            {{ post.content | linebreaks }}
                        </p>
                    </div>
                    <div class="card-footer d-flex justify-content-between"><p
                            class="card-text">{{ post.created_at }}</p>
                        <a href="{% url 'cooking:profile' user_id=post.author.pk %}">{{ post.author }}</a>
                        <p class="card-text">{{ post.watched }}</p>
                    </div>
                </div>
                <hr>

                <!--  reviews-->
                {% if request.user.is_authenticated %}
                    <form action="{% url 'cooking:add_comment' pk=post.pk %}" method="post"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include "components/_messages.html" %}
                        {{ comment_form.text }}
                        <button class="btn btn-dark" type="submit">Add comment</button>
                    </form>
                {% endif %}
                {% for comment in comments %}
                    <div class="card mt-2"><h5 class="card-header">{{ comment.user }} at {{ comment.created_at }}</h5>
                        <div class="card-body">
                            <p class="card-text">{{ comment.text }}</p>
                        </div>
                    </div>
                {% endfor %}


            </div>

            <!--  Recommendation-->
            <div class="col-1"></div>
            <div class="col-4">
                {% for post in post_recommends %}
                    <div class="card" style="width: 18rem;">
                        {% if post.photo %}
                            <img class="card-img-top"
                                 src="{{ post.photo.url }}"
                                 width="200" alt="">
                        {% else %}
                            <img src="https://i0.wp.com/castlewoodassistedliving.com/wp-content/uploads/2021/01/image-coming-soon-placeholder.png?fit=1000%2C1000&ssl=1"
                                 width="300"
                                 alt="">
                        {% endif %}
                        <div class="card-body"><h5 class="card-title">{{ post.title }}</h5><a
                                href="{{ post.get_absolute_url }}" class="btn btn-primary">More</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </main>
{% endblock %}

cooking/templates/cooking/profile.html
{% extends "base.html" %}
{% block title %}
    My profile
{% endblock %}

{% block main %}
    <div class="container">
        <div class="main-body">
            <div class="row gutters-sm">
                <div class="col-md-4 mb-3">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex flex-column align-items-center text-center">
                                <img src="https://www.pngall.com/wp-content/uploads/12/Avatar-Profile-PNG-Photos.png"
                                     alt="Admin" class="rounded-circle" width="150">
                                <div class="mt-3">
                                    <h4>{% firstof user.first_name user.username %}</h4>
                                    <p class="text-secondary mb-1">Developer</p>
                                    <p class="text-muted font-size-sm">Country, City</p>
                                    <button class="btn btn-primary">Follow</button>
                                    <button class="btn btn-outline-primary">Message</button>
                                </div>
                                <a href="{% url 'cooking:change_password' %}" class="dropdown-item">Change password</a>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="col-md-8">
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Full name</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {% firstof user.first_name user.username %}
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Email</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {% firstof user.email "Not added" %}
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Phone</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    +1111111111
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Mobile</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    +11111111111
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Address</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    Country, City
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-12">
                                    <a class="btn btn-info " target="__blank"
                                       href="https://www.bootdey.com/snippets/view/profile-edit-data-and-skills">Edit</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Author Posts-->
                    {% for post in posts %}
                        <div class="card p-3 mb-2">
                            <div class="d-flex justify-content-between">
                                <div class="card-text">{{ post.title }}</div>
                                <div class="d-flex justify-content-between">
                                    <div>Watched: {{ post.watched }}</div>
                                    {% if request.user == post.author %}
                                        <div>
                                            <a href="{% url 'cooking:post_update' pk=post.pk %}"
                                               class="btn btn-light"><i
                                                    class="fa-solid fa-pen-to-square fs-5"></i>Upd8</a>
                                        </div>
                                        <div>
                                            <a href="{% url 'cooking:post_delete' pk=post.pk %}" class="btn btn-light">
                                                <i class="fa-solid fa-xmark fs-5">Del</i>
                                            </a>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

cooking/templates/cooking/user_register.html
{% extends "base.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block main %}
    <div class="d-flex justify-content-center">
        <div class="card col-4 mb-4 mt-4">
            <div class="card-body">
                <h2 class="text-center">Register</h2>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-dark" type="submit">Register</button>
                </form>
            </div>
        </div>
    </div>
    <div>
        <div style="margin-top: 310px;"></div>
    </div>
{% endblock %}