cooking/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
from .views import *

app_name = "cooking"

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("category/<int:pk>/", PostsByCategory.as_view(), name="category_list"),
    path("post/<int:pk>/", PostDetail.as_view(), name="post_detail"),
    path("post/<int:pk>/update/", PostUpdate.as_view(), name="post_update"),
    path("post/<int:pk>/delete/", PostDelete.as_view(), name="post_delete"),
    path("add_post/", AddPost.as_view(), name="add_post"),
    path("search/", SearchResults.as_view(), name="search"),
    path("change_password/", UserChangePassword.as_view(), name="change_password"),

    path("post/<int:pk>/add_comment/", add_comment, name="add_comment"),
    path("login/", user_login, name="login"),
    path("logout/", user_logout, name="logout"),
    path("register/", user_register, name="register"),
    path("profile/<int:user_id>/", profile, name="profile"),

    # API
    path("api/posts/", PostListAPI.as_view(), name="posts_list_api"),
    path("api/posts/<int:pk>/", PostDetailAPI.as_view(), name="posts_detail_api"),
    path("api/categories/", CategoryListAPI.as_view(), name="category_list_api"),
    path("api/categories/<int:pk>/", CategoryDetailAPI.as_view(), name="category_detail_api"),

    # JWT
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

culinary/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("cooking.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/components/_messages.html
{% if messages %}
    <div class="message">
        {% for message in messages %}
            <div class="alert alert-{% if message.tags == error %}danger{% else %}{{ message.tags }}{% endif %}"
                 role="alert">
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %} 

templates/components/navbar.html
<header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'cooking:index' %}">Cooking</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'cooking:index' %}">Home</a>
                    </li>
                </ul>
                <form class="d-flex" role="search" method="get" action="{% url 'cooking:search' %}">
                    <input name="q" class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
                    <button class="btn btn-outline-success" type="submit">Search</button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            {% if not request.user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url "cooking:login" %}">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url "cooking:register" %}">Register</a>
                                </li>
                            {% else %}
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                       aria-expanded="false">
                                        Hello, {{ request.user.username }}
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" href="{% url 'cooking:profile' request.user.pk %}">My page</a></li>
                                        <li><a class="dropdown-item" href="{% url 'cooking:add_post' %}">Add post</a>
                                        </li>
                                        <li>
                                            <hr class="dropdown-divider">
                                        </li>
                                        <li><a class="dropdown-item" href="{% url "cooking:logout" %}">Logout</a></li>
                                    </ul>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </form>
            </div>
        </div>
    </nav>
</header>